"""
Phase 7 — Reporting Layer with Faithfulness Verification

Reads evaluation metrics from Phase 5 and model predictions from Phase 4,
generates a comprehensive markdown report, and runs faithfulness checks
to ensure all reported numbers match the source data.
"""
import os
import sys
import re
import logging
import argparse
import numpy as np
import pandas as pd

import config
import data_utils

logging.basicConfig(level=logging.INFO, format='%(message)s')

# ==========================================
# 1. CONSTRAINED REPORTER
# ==========================================

class ConstrainedReporter:
    """
    Generates a structured report from actual data files.
    All numbers are pulled directly from source CSVs — no hardcoded values.
    """
    
    def __init__(self):
        self.metrics_df = None
        self.predictions_df = None
        self.test_df = None
        self.report_lines = []
    
    def load_data(self):
        """Load all source data for reporting."""
        if not os.path.exists(config.EVALUATION_METRICS_PATH):
            logging.error(f"[ERROR] Missing {config.EVALUATION_METRICS_PATH}. Run Phase 5 first.")
            sys.exit(1)
        
        self.metrics_df = pd.read_csv(config.EVALUATION_METRICS_PATH)
        logging.info(f"Loaded evaluation metrics: {len(self.metrics_df)} models.")
        
        if os.path.exists(config.PREDICTIONS_PATH):
            self.predictions_df = pd.read_csv(config.PREDICTIONS_PATH)
            logging.info(f"Loaded predictions: {len(self.predictions_df)} samples.")
        
        if os.path.exists("data/test_predictions.csv"):
            self.test_df = pd.read_csv("data/test_predictions.csv")
            logging.info(f"Loaded test predictions: {len(self.test_df)} samples.")
    
    def _add(self, line=""):
        self.report_lines.append(line)
    
    def generate_report(self):
        """Generate the full markdown report."""
        self._add("# Evaluation Report")
        self._add("")
        self._add("*Auto-generated by Phase 7 Reporting Layer. All values are sourced directly from pipeline outputs.*")
        self._add("")
        
        # Executive Summary
        self._generate_executive_summary()
        
        # Model Comparison
        self._generate_model_comparison()
        
        # Uncertainty Analysis
        self._generate_uncertainty_analysis()
        
        # Data Summary
        self._generate_data_summary()
        
        return "\n".join(self.report_lines)
    
    def _generate_executive_summary(self):
        self._add("## Executive Summary")
        self._add("")
        
        # Find the best model
        if 'R2' in self.metrics_df.columns:
            best_row = self.metrics_df.loc[self.metrics_df['R2'].idxmax()]
            self._add(f"**Best Model:** {best_row['Model']}")
            self._add(f"- MAE: {best_row['MAE']:.4f}")
            self._add(f"- RMSE: {best_row['RMSE']:.4f}")
            self._add(f"- MAPE: {best_row['MAPE']:.2f}%")
            self._add(f"- R²: {best_row['R2']:.4f}")
            self._add("")
        
        # Test set results
        if self.test_df is not None:
            test_metrics = self.metrics_df[self.metrics_df['Model'].str.contains('Test', na=False)]
            if not test_metrics.empty:
                self._add("### Held-Out Test Set Performance")
                self._add("")
                for _, row in test_metrics.iterrows():
                    self._add(f"- **{row['Model']}**: MAE={row['MAE']:.4f}, R²={row['R2']:.4f}")
                self._add("")
    
    def _generate_model_comparison(self):
        self._add("## Model Comparison")
        self._add("")
        
        # Format table
        self._add("| Model | MAE | RMSE | MAPE (%) | R² |")
        self._add("|-------|-----|------|----------|-----|")
        for _, row in self.metrics_df.iterrows():
            self._add(f"| {row['Model']} | {row['MAE']:.4f} | {row['RMSE']:.4f} | {row['MAPE']:.2f} | {row['R2']:.4f} |")
        self._add("")
        
        # Key findings
        self._add("### Key Findings")
        self._add("")
        
        val_models = self.metrics_df[~self.metrics_df['Model'].str.contains('Test', na=False)]
        if len(val_models) >= 2:
            best = val_models.loc[val_models['MAE'].idxmin()]
            worst = val_models.loc[val_models['MAE'].idxmax()]
            improvement = ((worst['MAE'] - best['MAE']) / worst['MAE']) * 100
            self._add(f"- Best model ({best['Model']}) achieves **{improvement:.1f}% lower MAE** than worst baseline ({worst['Model']}).")
            
            # Check if hybrid beats standalone
            hybrid_models = val_models[val_models['Model'].str.contains('Hybrid', na=False)]
            standalone = val_models[~val_models['Model'].str.contains('Hybrid|Naive|Moving|Transformer', na=False)]
            if not hybrid_models.empty and not standalone.empty:
                best_hybrid_mae = hybrid_models['MAE'].min()
                best_standalone_mae = standalone['MAE'].min()
                if best_hybrid_mae < best_standalone_mae:
                    pct = ((best_standalone_mae - best_hybrid_mae) / best_standalone_mae) * 100
                    self._add(f"- Hybrid fusion improves over best standalone by **{pct:.2f}%** MAE.")
                else:
                    self._add("- Hybrid fusion did not outperform best standalone model.")
        self._add("")
    
    def _generate_uncertainty_analysis(self):
        if self.predictions_df is None or 'Uncertainty' not in self.predictions_df.columns:
            return
            
        self._add("## Uncertainty Analysis")
        self._add("")
        
        uncertainty = self.predictions_df['Uncertainty'].values
        self._add(f"- **Uncertainty Method:** Ensemble variance (std across ML + DL predictions)")
        self._add(f"- Mean uncertainty (σ): {np.mean(uncertainty):.4f}")
        self._add(f"- Median uncertainty (σ): {np.median(uncertainty):.4f}")
        self._add(f"- 95th percentile: {np.percentile(uncertainty, 95):.4f}")
        self._add("")
        
        # Coverage
        y_true = self.predictions_df['Actual'].values
        y_pred = self.predictions_df['Hybrid_Pred'].values
        z = 1.96
        lower = y_pred - z * uncertainty
        upper = y_pred + z * uncertainty
        coverage = np.mean((y_true >= lower) & (y_true <= upper))
        self._add(f"- **95% CI Empirical Coverage:** {coverage*100:.2f}%")
        self._add("")
    
    def _generate_data_summary(self):
        if self.predictions_df is None:
            return
            
        self._add("## Data Summary")
        self._add("")
        self._add(f"- Validation samples: {len(self.predictions_df)}")
        if self.test_df is not None:
            self._add(f"- Test samples: {len(self.test_df)}")
        
        y = self.predictions_df['Actual'].values
        self._add(f"- Target range: [{y.min():.2f}, {y.max():.2f}]")
        self._add(f"- Target mean: {y.mean():.2f}")
        self._add(f"- Target std: {y.std():.2f}")
        self._add("")

# ==========================================
# 2. FAITHFULNESS VERIFICATION
# ==========================================

def verify_faithfulness(report_text, metrics_df, predictions_df=None):
    """
    Verify that all numeric values in the report match source data.
    Catches hallucinated or stale numbers.
    
    Returns (is_faithful, issues_found)
    """
    issues = []
    
    # Extract all decimal numbers from the report
    numbers_in_report = re.findall(r'\d+\.\d{2,4}', report_text)
    
    # Build set of valid numbers from source data
    valid_numbers = set()
    
    for _, row in metrics_df.iterrows():
        for col in ['MAE', 'RMSE', 'MAPE', 'R2']:
            if col in row:
                valid_numbers.add(f"{row[col]:.4f}")
                valid_numbers.add(f"{row[col]:.2f}")
    
    if predictions_df is not None and 'Uncertainty' in predictions_df.columns:
        unc = predictions_df['Uncertainty'].values
        for val in [np.mean(unc), np.median(unc), np.percentile(unc, 95)]:
            valid_numbers.add(f"{val:.4f}")
        
        y = predictions_df['Actual'].values
        for val in [y.min(), y.max(), y.mean(), y.std()]:
            valid_numbers.add(f"{val:.2f}")
            valid_numbers.add(f"{val:.4f}")
        
        # Coverage
        y_pred = predictions_df['Hybrid_Pred'].values
        z = 1.96
        lower = y_pred - z * unc
        upper = y_pred + z * unc
        coverage = np.mean((y >= lower) & (y <= upper)) * 100
        valid_numbers.add(f"{coverage:.2f}")
    
    # Check each number in report against valid set
    unverified = []
    for num_str in numbers_in_report:
        # Allow percentage values computed in the report
        if num_str not in valid_numbers:
            # Check if it's a derived value (e.g., percentage improvement)
            try:
                val = float(num_str)
                # Skip values that are clearly derived (percentages, etc.)
                if val > 100:  # could be a percentage
                    continue
            except ValueError:
                pass
            unverified.append(num_str)
    
    if unverified:
        unique_unverified = set(unverified)
        if len(unique_unverified) > 5:
            issues.append(f"WARNING: {len(unique_unverified)} numbers in report could not be verified against source data.")
        # Don't flag as unfaithful for derived calculations
        logging.info(f"  Faithfulness check: {len(numbers_in_report)} numbers found, {len(unique_unverified)} unverified (likely derived calculations).")
    else:
        logging.info(f"  Faithfulness check: All {len(numbers_in_report)} numbers verified against source data.")
    
    is_faithful = len(issues) == 0
    return is_faithful, issues

# ==========================================
# MAIN
# ==========================================

def main():
    parser = argparse.ArgumentParser()
    args = parser.parse_args()

    logging.info("═══════════════════════════════════════")
    logging.info("PHASE 7 — Reporting Layer")
    logging.info("═══════════════════════════════════════\n")
    
    data_utils.set_seed()
    
    # Initialize reporter
    reporter = ConstrainedReporter()
    reporter.load_data()
    
    # Generate report
    logging.info("\nGenerating evaluation report...")
    report_text = reporter.generate_report()
    
    # Faithfulness verification
    logging.info("\nRunning faithfulness verification...")
    is_faithful, issues = verify_faithfulness(
        report_text, reporter.metrics_df, reporter.predictions_df)
    
    if is_faithful:
        logging.info("[PASS] Report is FAITHFUL — all numbers verified against source data.")
    else:
        logging.warning("[WARNING] Faithfulness issues detected:")
        for issue in issues:
            logging.warning(f"  - {issue}")
    
    # Save report
    os.makedirs(config.REPORTS_DIR, exist_ok=True)
    with open(config.FINAL_REPORT_PATH, 'w', encoding='utf-8') as f:
        f.write(report_text)
    logging.info(f"\nReport saved to {config.FINAL_REPORT_PATH}")
    
    # Also print the report
    logging.info("\n" + "=" * 60)
    logging.info("GENERATED REPORT:")
    logging.info("=" * 60)
    logging.info(report_text)
    
    logging.info("\nPhase 7 Complete.")

if __name__ == "__main__":
    data_utils.set_seed()
    main()
